### ISSUE TITLE
source "//" yield "Unexpected token (1:12)"

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#10]
Hello, it's me again

i found that "//" yield "Unexpected token (1:12)", while "//" + "\n" does not yield error

to me both should work, is this an issue?

**Comment by bplok20010** [comment]
@lab4quant  can you provide an example?

**Comment by lab4quant** [comment]
@bplok20010 , you may use my [notebook](https://quantlib.js.org/notebook/), create a cell
try 
* "//" , which yields error
* "// + enter", which yields 'undefined',

**Comment by lab4quant** [comment]
btw, i noticed that whenever there's error in `evaluation()`, `column` info in error message is not accurate, e.g. the error in this ticket `(1:12)`, it's line1 and column12? there're only 2 characters

**Comment by bplok20010** [comment]
@lab4quant 

error reason:
```
eval5.evaluate(`with(ql){${o}}`)
// equal:
eval5.evaluate(`with(ql){//}`)
```

you can try `rootcontext` instead of `with (ql){...}`
eg:
```
new Interpreter(ctx, {
rootContext: ql
})
```

**Comment by lab4quant** [comment]
@bplok20010 , awesome, it's really handy feature `rootContext`
is it possible for `window.eval`?

**Comment by lab4quant** [comment]
it seems, it works sometimes only, when using `rootContext` and drop `with(ql){}`

![image](https://user-images.githubusercontent.com/29996911/79294827-b1a47600-7f09-11ea-8c93-e4526608263d.png)

**Comment by bplok20010** [comment]
@lab4quant 
the export objects may be special.
you can try this, my environment test ok.
```
 import(
    "https://cdn.jsdelivr.net/npm/@quantlib/ql@latest/ql.mjs"
).then(function (e) {
   var ql = {};
   // copy to ql
   Object.keys(e).forEach((key) => (ql[key] = e[key]));
   ....
   new Interpreter(ctx, {
      rootContext: ql
   })
})
```
of course, you can continue to use `with`

**Comment by lab4quant** [comment]
@bplok20010 , cool, this is an acceptable workaround, i'll watch it for a while, see if any other issue
thanks!
