### ISSUE TITLE
minor for loop evaluation issue

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#11]
Hello, it's me again

I found a minor issue in for-loop:

![image](https://user-images.githubusercontent.com/29996911/80176935-b3b6b500-862c-11ea-9aa2-ba131ea1bdaa.png)

the 3rd for-loop, evaluation result is 100, should it be undefined like the other 2 for-loop cases?

**Comment by bplok20010** [comment]
@lab4quant 
the result is right, `data.push(i)` is the last expression.

**Comment by lab4quant** [comment]
@bplok20010 thanks, i just tried in browser console, it's the same, closing ticket
