### ISSUE TITLE
exponential operator ** not working

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#12]
Hi, it's me again:

![image](https://user-images.githubusercontent.com/29996911/80779336-f254ee00-8b9d-11ea-9f5e-5f0c1329e225.png)

1st cell using `eval5`, 2nd cell using `eval`

**Comment by bplok20010** [comment]
es5 syntax only

**Comment by lab4quant** [comment]
oh, ok, i thought `**` was there all the time
