### ISSUE TITLE
干的漂亮！

### ISSUE THREAD

**Issue by IAIAE** [bplok20010/eval5#13]
小程序社区上看到过来。其实很想在社区评论，怕这东西被关注太多导致小程序的抵制措施，就没评论。

两千行代码就完成了js整个运行栈的模拟，看得心痒痒。想自己边撸边学，能推荐相关基础知识点的学习资料么？怎么穷举各种closure的处理情况的，是有相应标准么？十分感谢~~

**Comment by bplok20010** [comment]
不需要什么特殊知识，不过这种解释器应该是叫：自循环解释器。

**Comment by IAIAE** [comment]
嗯，已经动手开始写了。在你这个的基础上加入es2015的支持：
https://github.com/IAIAE/estime

**Comment by bplok20010** [comment]
> 嗯，已经动手开始写了。在你这个的基础上加入es2015的支持：
> https://github.com/IAIAE/estime

加油！
