### ISSUE TITLE
所以这种东西可以通过审核吗

### ISSUE THREAD

**Issue by Gunkkk** [bplok20010/eval5#15]
有人尝试过应用和提交在wx上吗

**Comment by Thinking80s** [comment]
同问这个情况能否通过微信的审核？

**Comment by bplok20010** [comment]
我还没实践过，不过这只是个常规的JS库，应该是不影响审核的。

**Comment by crny** [comment]
用了，没问题

**Comment by Gunkkk** [comment]
> 用了，没问题

能不能透露下什么小程序

**Comment by robin-shine** [comment]
这个微信可以过审吗？应该有被封禁的风险吧？

**Comment by fangyongbao** [comment]
这个微信可以过审吗？应该有被封禁的风险吧

**Comment by beilunyang** [comment]
同问，这东西有封禁的风险吗，有用了的同学分享下使用感受和经验吗

**Comment by foolzhang** [comment]
用来搞小程序热修复么？

**Comment by beilunyang** [comment]
> 用来搞小程序热修复么？

主要用来扩展功能的，有时候也用来热修复bug

**Comment by CodingYiyi** [comment]
> 用了，没问题

偷偷问下，现在还在正常使用吗？
 @Gunkkk 你们有尝试经验可以分享一下吗？

**Comment by Foolyou** [comment]
https://developers.weixin.qq.com/community/minihome/doc/0000ae500e4fd0541f2ea33755b801

GG了

**Comment by wozien** [comment]
g
