### ISSUE TITLE
测试发现不支持**2，**3平方运算？

### ISSUE THREAD

**Issue by XuZhiFan** [bplok20010/eval5#17]

**Comment by XuZhiFan** [comment]
const interpreter = new Interpreter(window, {
				timeout: 1000,
				ecmaVersion:7
			});
			console.log(interpreter.evaluate('10**2'));
这样处理就可以了

**Comment by bplok20010** [comment]
但还是不建议这么做，eval5语法只支持到es5，开启ecmaVersion7后可能导致新语法的不支持
