### ISSUE TITLE
不支持函数上下文

### ISSUE THREAD

**Issue by Z1hgq** [bplok20010/eval5#21]
![image](https://user-images.githubusercontent.com/26574371/131641209-6a81fa07-1585-4dff-8e0f-2bbcd03da130.png)

**Comment by bplok20010** [comment]
你需要设置`globalContextInFunction`

## globalContextInFunction

默认值: undefined

eval5 不支持 use strict 严格模式, 在非严格下的函数中this默认指向的是全局作用域，** 但在eval5中是undefined **， 可通过globalContextInFunction来设置默认指向。

**Comment by Z1hgq** [comment]
有找到这个，谢谢

随心 ***@***.***> 于2021年9月2日周四 下午6:15写道：
