### ISSUE TITLE
疑问，跟 eval 这个库有什么区别

### ISSUE THREAD

**Issue by RolkerMan** [bplok20010/eval5#23]
https://www.npmjs.com/package/eval

请问这个仓库跟这个开源项目有什么异同?
最好在项目  README 上说明下

**Comment by bplok20010** [comment]
场景和实现已经在md说明，
eval5: 使用基于 TypeScript 编写的 JavaScript 解释器来解析 js
eval: 使用 node 的 vm 模块来解释 js
