### ISSUE TITLE
最新的微信小程序审核未能通过。

### ISSUE THREAD

**Issue by mooseIre** [bplok20010/eval5#29]
你好，当前提审的小程序包中可能含有页面文件采用内置 JavaScript 解释器（如eval5、estime、evil-eval等）的方式，动态执行JS代码、对小程序wxml代码进行热更新。出于安全考虑，建议你立即调整技术方案，去除相关内容，消除风险

**Comment by bplok20010** [comment]
很遗憾！小程序已经添加了对 JavaScript 解释器（如eval5、estime、evil-eval等）的检查识别。

**Comment by mooseIre** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Wangjian-damon** [comment]
> 

请问大佬知道检测规则吗？是针对包名检测还是啥

**Comment by bplok20010** [comment]
现在js解释器运行原理来讲，wx底层是无法感知你用了解释器，检测可能是来自关键字(如:eval5)、代码片段(如:内部方法名称等)。可自定义修改或进一步混淆(仅猜测)。
**由于官方已经明确禁止微信小程序使用解释器，慎用！**
