### ISSUE TITLE
question: how does Interpreter.global work?

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#3]
Hello, I see you've closed my previous ticket with a commit, when fix will be released, thanks!

A question: how does Interpreter.global work?

right now, i'm using `new Interpreter(window)` which is working

i also tried loading a external lib using dynamic `import()`, and `new Interpreter(module)` inside import promise, so when i call `evaluate()`, i don't need to prefix module name in the class, like this `var obj = new ql.ClassName()` and use `var obj = new ClassName()` directly

```js
var interperter;
import('url-to-js-lib')
.then(module=>{
interperter = new eval5.Interpreter(module);
})
```
after module is loade, when calling `evaluate()`, i'm getting: `cannot add property obj, object is not extensible`

how to make this work? thanks!

**Comment by bplok20010** [comment]
try this
```
var interperter;
import('eval5')
.then(eval5=>{
interperter = new eval5.Interpreter(window);
})
```

**Comment by bplok20010** [comment]
`Interpreter.global` is the default context.
```
class Interpreter {
  ...
  constructor(context = Interpreter.global, ...){...}
 ...
}
```

examples:
```
Interpreter.global = window;
new Interpreter();
//equal
new Interpreter(window);
```

**Comment by lab4quant** [comment]
thanks for the update, i meant, is there anyway i can create a context without involving `window`?

say, i have a library `ql`, loaded from external link, can i create a context in `ql`?

my notebook app link: https://quantlib.js.org/notebook
tutorial:  https://quantlib.js.org/notebook/#hello.json

**Comment by bplok20010** [comment]
```
var ctx = Object.create(ql);
var interpreter = new eval5.Interpreter(ctx);
interpreter.evaluate(`
var today = DateExt.UTC('7,March,2014');
Settings.evaluationDate.set(today);
today;
`);
```

**Comment by lab4quant** [comment]
@bplok20010 , awesome, this is what i need!

**Comment by lab4quant** [comment]
@bplok20010, sorry, i closed it too fast
when using suggested approach, it only works sometimes, i couldn't run all the code from `tutorial` above, browser tab will crash, at this cell:
![image](https://user-images.githubusercontent.com/29996911/76411175-33b1f400-63cc-11ea-90c1-4c5be82ae94b.png)

but if i'm using `window`, everything works fine

**Comment by bplok20010** [comment]
How do I reproduce? Can you provide examples?

**Comment by lab4quant** [comment]
@bplok20010, i released a temporary version: https://quantlib.js.org/notebook/ql.html
and update notebook: https://quantlib.js.org/notebook/ql.html#ql.json

**Comment by bplok20010** [comment]
I have seen your page. 
I suggest you use the following code
```
window.ql = ql;
var ctx = window;
// or
// var ctx = Object.create(window);
// ctx.eval = undefined;
var interpreter = new eval5.Interpreter(ctx);
interpreter.evaluate(`
 with(ql) {
${code}
}
`)
```
Because I see that you have mounted related variables to the window, such as plot.

In the end I didn't find the cause of the crash because the ql is too large

**Comment by lab4quant** [comment]
@bplok20010 , thanks a lot, now it works!
