### ISSUE TITLE
执行eval时报栈溢出

### ISSUE THREAD

**Issue by chigend** [bplok20010/eval5#31]
你好请问一般什么情况下会出现栈溢出啊
<img width="389" alt="image" src="https://user-images.githubusercontent.com/19338606/206445371-26f7d014-f9f1-4974-98ba-8f1ee3eb6207.png">

不知道哪里的语法有问题导致的呢

**Comment by chigend** [comment]
看了下js本身是没有 递归调用的

**Comment by bplok20010** [comment]
贴下运行代码，截图信息看不出什么问题

> 看了下js本身是没有 递归调用的

**Comment by chigend** [comment]
https://github.com/chigend/demo/blob/master/background.js  你好我上传github了  麻烦有空的时候帮忙看看  谢谢了

**Comment by bplok20010** [comment]
函数调用栈溢出！暂时我也没办法处理。
建议：JS库不用放到eval5里执行，在实例解释器时，可以将库导出的对象挂在到作用域上，只解析你业务相关的代码试试

**Comment by chigend** [comment]
谢谢你的回复, 不过我不太懂具体的实现是怎么样的呢, 是指原本在业务代码中 通过类似import _ from  'lodash' 等的代码去掉吗，有没有相关的例子呢

**Comment by bplok20010** [comment]
类似这样：
```
const interpreter = new Interpreter({
   _: lodash
});

interpreter.eval(' _.isObject()... ')
```

至于代码文件里的 `import _ from 'lodash'`要不要去掉，就根据你的构建工具配置了

> 谢谢你的回复, 不过我不太懂具体的实现是怎么样的呢, 是指原本在业务代码中 通过类似import _ from 'lodash' 等的代码去掉吗，有没有相关的例子呢
