### ISSUE TITLE
存在沙盒逃逸和CSP Bypass风险

### ISSUE THREAD

**Issue by ttttmr** [bplok20010/eval5#32]
沙盒环境可以通过访问原型链获取`Function`，进一步执行JS代码

```js
Object.prototype.constructor.constructor("return eval")()("alert(1)")
```

即使在非常严格的CSP防护下，比如`script-src 'self' 'wasm-unsafe-eval'; object-src 'self'`，也存在通过原型链污染的方式进行逃逸，从而进一步执行JS代码

详细可见 https://blog.xlab.app/p/766bba8a/

**Comment by bplok20010** [comment]
感谢指出，文章写得很棒！这个问题确实存在，eval5的内置对象使用当前环境所提供的，目前无法避免。
