### ISSUE TITLE
你试试转义这个就炸了

### ISSUE THREAD

**Issue by VcrTing** [bplok20010/eval5#34]
const a = "{'codeParam':'Bdate','nameParam':''}"
// 转义a

var interpreter = new Interpreter({});
const b = interpreter.evaluate(a);

**Comment by bplok20010** [comment]
首尾的{}会当做块级作用域，试试
```
const a = "({'codeParam':'Bdate','nameParam':''})"
// 转义a

var interpreter = new Interpreter({});
const b = interpreter.evaluate(a);
```
