### ISSUE TITLE
1.3.1 broken?

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#5]
sorry to bother you again, i just found 1.3.1 released, i assumed my previous ticket is fixed with it

when i load with 1.3.1, the #3 we discussed before stopped working ...

html file can be downloaded from https://github.com/quantlibjs/notebook, and test locally with browser, if you change eval5 to 1.3.1, it stops working, the classes under `ql` could not be found

**Comment by bplok20010** [comment]
my computer works.

![image](https://user-images.githubusercontent.com/4351621/76593557-a1c3fb80-6531-11ea-9259-c60812ae8dcc.png)


![image](https://user-images.githubusercontent.com/4351621/76593387-28c4a400-6531-11ea-8563-0d4be8e36159.png)

**Comment by bplok20010** [comment]
https://bplok20010.github.io/notebook/#hello.json

**Comment by lab4quant** [comment]
@bplok20010 , sorry, it was my problem, i was testing a local version, the code is different
