### ISSUE TITLE
minor evaluate() result issue

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#6]
Hello, it's me again :)

i added `typescript` in my notebook, code is transpiled then feed to `eval5`

pls refer to below result, i checked ts transpile code, the class inherit generated 2 `var`statements, i'm expecting cell ouput to be `undefined`

also, if 2nd cell is executed again, the output changed to `undefined`

please take a look, thanks!

link: https://quantlib.js.org/notebook/

![image](https://user-images.githubusercontent.com/29996911/76758799-6e010400-67c5-11ea-803b-3c23f481b474.png)

**Comment by bplok20010** [comment]
Fixed, but you need to upgrade to v1.4.1
