### ISSUE TITLE
evaluation / execution result issue

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#7]
Hello, it's me again

for my [notebook app](https://quantlib.js.org/notebook/), i have render api `print()`, which print number/string to cell output
![image](https://user-images.githubusercontent.com/29996911/78142184-2a61f780-745f-11ea-8242-80435e2c5a4a.png)

it doesn't look right to me, i remember this use to work in older version, i'm sure old version works for last cell: print in a look, my `print()` api, uses `append`, if it's called multiple times, all should go to output

as for 3rd cell, the evaluation result is undefined, this is correct, however `print` not fired, pls take a look, thanks!

**Comment by bplok20010** [comment]
I don't quite understand what you mean, but your screenshot output is correct.

**Comment by lab4quant** [comment]
* `cell1`  to demonstrate `print()`
* `cell2` wrap `print()` in a function
* `cell3` call function created in `cell2`, `print()` not called?
* `cell4` `print()` called multiple times in a look, only got last result

**Comment by bplok20010** [comment]
`print()` will be called for each cell execution, but the interpreter will only return the execution result of the current cell.
your print function may need to be implemented as follows:
```
var currentCell = 0;
function print(){
     $('#'+currentCell ).append(result)
}
```
```
currentCell = ?;// 1 2 3 4 ...
$('#'+currentCell ).empty()
interpreter.evaluate(code); // 
currentCell = 0;
```

**Comment by lab4quant** [comment]
@bplok20010 , thanks, i see, i forgot i changed `print()` implementation before, this part is not eval5 issue
