### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#8]
Hello, it's me again

i have code that does monte carlo simulation, in `node.js` it takes about 8 seconds, while in my [notebook app](https://quantlib.js.org/notebook/) using `eval5`, it takes 95+ seconds, the difference is quite big

i'm aware that using a js interpreter will slow things down, but i have a library of my own, if i call functions from my own lib, that part is executed by browser directly, right? or my understanding is totally wrong?

i don't know if this is related at all, when using eval5, the performance is similar of using `quickjs` which has no `JIT` feature

**Comment by bplok20010** [comment]
Your understanding is right

Time consuming computational functions should not be parsed by eval5

**Comment by lab4quant** [comment]
pls take a look at uploaded sample [discretehedging.zip](https://github.com/bplok20010/eval5/files/4418061/discretehedging.zip), it's modified based on [this example](https://github.com/quantlibjs/examples/blob/master/discretehedging.mjs)

it created 2 classed, and almost all the work is done by `ql`, it just call the API.

after parsing by eval5, the rest should be fast, any way to improve the performance from my code?

thanks!

**Comment by lab4quant** [comment]
i added the notebook to github page:
https://quantlib.js.org/notebook/#quantlib/discretehedging.json

my previous timing wasn't right, that 95+ seconds was run on firefox, while in chrome, build with same v8 engine as node.js, it's a lot faster, on my computer it's 50+ seconds

**Comment by bplok20010** [comment]
i try to run this code with window.eval, which also takes 20-40 seconds.

**Comment by lab4quant** [comment]
@bplok20010 ,how did you do that using `window.eval`?

**Comment by bplok20010** [comment]
@lab4quant  copy page code, local debugging

**Comment by lab4quant** [comment]
sorry, i've been busy recently. i tried myself, but it seems difficult to use `window.eval` to achieve the same functionality, the variables created from code cells always go to `window`, did you prefix `ql.` to all classes in the code? do you mind sharing your code?

**Comment by bplok20010** [comment]
@lab4quant 
This is a test I ran directly with window.eval
https://bplok20010.github.io/notebook/#quantlib/discretehedging.json

repo: 
https://github.com/bplok20010/notebook
---
it can't solve your sandbox problem，test execution time only.

eval5 is 2-10+times less efficient than window.eval

**Comment by lab4quant** [comment]
@bplok20010, thanks a lot!
it only takes 14 seconds on my computer, just a few seconds more than node.js
i might add window.eval to notebook, as one of the options

**Comment by lab4quant** [comment]
looks like i thought too much, with your approach, it works, but all variables are created under `window`, i guess this is acceptable. is it possible to use `window.eval` like your lib `eval5`, i mean do things in a seperate `context`

**Comment by bplok20010** [comment]
Can not

>  i mean do things in a seperate `context`

**Comment by lab4quant** [comment]
@bplok20010 , thanks a lot for your help, closing ticket
