### ISSUE TITLE
variable scope issue: Cannot add property i, object is not extensible

### ISSUE THREAD

**Issue by lab4quant** [bplok20010/eval5#9]
Hello, it's me again

I found another issue: https://quantlib.js.org/notebook/#tutorial.en.json

1. run code cells backwards, there will be error messages saying something not defined, ignore
2. run code cells forward, till last one with plot, there will be error message: `Cannot add property i, object is not extensible`

i checked `interpreter.globalContext` in browser console, `i` used in for-loop is in global context, i don't think this is right

**Comment by bplok20010** [comment]
@lab4quant 
I found the reason. I'll fix it tonight. Thank you
